import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Query } from "appwrite";
import { QueryProvider } from "@/lib/react-query/QueryProvider";
import PageAccueil from "./accueil/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          {/* <div> */}
          <header>
              <PageAccueil /> 
          </header>

            {children}

          <footer>
            <p>Footer</p>
          </footer>
            {/* </div> */}
        </QueryProvider>
      </body>
    </html>
  );
}
